---
- name: Add fish repo
  ansible.builtin.apt_repository:
    repo: "{{ fish_ppa_repo }}"
  become: true
  when:
    - ansible_distribution == "Ubuntu"

- name: Update packages cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when:
    - ansible_distribution == "Ubuntu"

- name: Install fish
  ansible.builtin.package:
    name: "{{ fish_packages }}"
    state: present
  become: "{{ ansible_distribution != 'MacOSX' }}"
  when:
    - ansible_distribution != "NixOS"

- name: Create fish config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ fish_config_dir }}"
    - "{{ fish_config_dir }}/conf.d"

- name: Configure
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  loop:
    - src: config.fish.j2
      dest: "{{ fish_config_dir }}/config.fish"
    - src: config.fish.j2
      dest: "{{ fish_config_dir }}/functions/fish_right_prompt.fish"
    - src: env.fish.j2
      dest: "{{ fish_config_dir }}/conf.d/env.fish"
    - src: alias.fish.j2
      dest: "{{ fish_config_dir }}/conf.d/alias.fish"
    - src: theme.j2
      dest: "{{ fish_config_dir }}/conf.d/theme.fish"

- ansible.builtin.import_tasks: fisher.yml
