---

neovim_config_path: "{{ lookup('env', 'HOME') }}/.config/nvim"
neovim_plugins_dir: >-
  {{ lookup('env', 'HOME') }}/.local/share/nvim/plugged
neovim_plug_dir: >-
  {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload
neovim_plug_url: >-
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
neovim_the_silver_searcher_package_name: >-
  {{ 'silversearcher-ag'
     if ansible_distribution == 'Ubuntu'
     else 'the_silver_searcher' }}
