---

neovim_config_repo: "https://github.com/cornBuddy/nvim-config"
neovim_config_path: "{{ lookup('env', 'HOME') }}/.config/nvim"
neovim_packages:
  - neovim
  - delve
neovim_packer_repo: https://github.com/wbthomason/packer.nvim.git
neovim_packer_path: >-
  {{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim
