---
neovim_packages:
  - nvim
neovim_config_repo: "git@github.com:cornBuddy/nvim-config.git"
neovim_config_path: "{{ ansible_env.HOME }}/.config/nvim"

neovim_plug_url: >-
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
neovim_plug_path: >-
  {{ ansible_env.HOME }}/.local/share/nvim/site/autoload/
