---

neovim_config_path: "{{ lookup('env', 'HOME') }}/.config/nvim"
neovim_plug_dir: >-
  {{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload
neovim_plug_url: >-
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
