---
- name: add pikaos repo
  deb822_repository:
    name: pikaos
    types: deb
    uris: https://ppa.pika-os.com
    suites: pikauwu
    signed_by: https://ppa.pika-os.com/key.gpg
    components:
      - main
      - external
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: install hyprland packages
  ansible.builtin.package:
    name: "{{ hyprland_packages }}"
    state: present
  become: true
  when: ansible_distribution != 'NixOS'

- name: create hyprland directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ hyrpland_confid_dir }}"
    - "{{ hyprland_waybar_config_dir }}"
    - "{{ hyprland_wlogout_config_dir }}"

# TODO:
# * date format
# * disk usage
# * styles
- name: configure hyprland
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: hyprland.conf.j2
      dest: "{{ hyrpland_confid_dir }}/hyprland.conf"
    - src: hotkeys.conf.j2
      dest: "{{ hyrpland_confid_dir }}/hotkeys.conf"
    - src: wlogout/layout.j2
      dest: "{{ hyprland_wlogout_config_dir }}/layout"
    - src: waybar/config.j2
      dest: "{{ hyprland_waybar_config_dir }}/config"
    - src: waybar/style.css.j2
      dest: "{{ hyprland_waybar_config_dir }}/style.css"
