---
fish_ppa_repo: ppa:fish-shell/release-3
fish_packages:
  - fish

fish_config_dir: "{{ lookup('env', 'HOME') }}/.config/fish"

fish_fisher_plugins:
  - jorgebucaran/fisher
  - jorgebucaran/autopair.fish
  - pure-fish/pure
  - evanlucas/fish-kubectl-completions

fish_go_root: /opt/go
fish_go_path: "{{ ansible_env.HOME }}/go"
fish_local_bin_path: "{{ ansible_env.HOME }}/.local/bin"
