---

- hosts: localhost
  gather_facts: true
  tasks:
    - name: Set timezone
      file:
        state: link
        src: /usr/share/zoneinfo/Europe/Minsk
        dest: /etc/localtime
      become: true
      when: ansible_distribution != 'MacOSX'
  roles:
    - role: zsh
      tags: zsh
    - role: user
      tags: user
      when: ansible_distribution != 'MacOSX'
    - role: package-manager
      tags: package-manager
      when: ansible_distribution != 'MacOSX'
    - role: neovim
      tags: neovim
    - role: tmux
      tags: tmux
    - role: window-manager
      tags: window-manager
      when: ansible_distribution != 'MacOSX'
    - role: alacritty
      tags: alacritty
