---

- hosts: localhost
  pre_tasks:
    - name: Upgrade system
      pacman:
        update_cache: true
        upgrade: true
      become: true
  roles:
    - role: zsh
    - role: neovim
    - role: tmux
    - role: window-manager
    - role: alacritty
