---

- hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Set timezone
      file:
        state: link
        src: /usr/share/zoneinfo/Europe/Minsk
        dest: /etc/localtime
      become: true
  roles:
    - role: user
      tags: user
    - role: package-manager
      tags: package-manager
    - role: neovim
      tags: neovim
    - role: tmux
      tags: tmux
    - role: window-manager
      tags: window-manager
    - role: alacritty
      tags: alacritty
