---

- hosts: localhost
  pre_tasks:
    - name: Set timezone
      file:
        state: link
        src: /usr/share/zoneinfo/Europe/Minsk
        dest: /etc/localtime
      become: true
  roles:
    - role: user
    - role: package-manager
    - role: neovim
    - role: tmux
    - role: window-manager
    - role: alacritty
