---
- name: provision workstation
  hosts: localhost
  gather_facts: true
  roles:
    - role: packages
      vars:
        packages_nix_flake_path: "{{ playbook_dir }}/toolbox-flake"

    - role: ubuntu
      vars:
        user_shell: "{{ ansible_env.HOME }}/.nix-profile/bin/fish"
      tags: distro
      when: ansible_distribution == 'Ubuntu'
