---
- name: Create group
  ansible.builtin.group:
    name: "{{ user_primary_group }}"
    gid: "{{ user_group_id }}"
  become: true

- name: Create secondary groups
  ansible.builtin.group:
    name: "{{ item }}"
  loop: "{{ user_secondary_groups }}"
  become: true

- name: Create user
  ansible.builtin.user:
    group: "{{ user_primary_group }}"
    groups: "{{ user_secondary_groups }}"
    name: "{{ user_name }}"
    uid: "{{ user_id }}"
    shell: "{{ user_shell }}"
  become: true

- name: Set defaults
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ user_name }}
    line: Defaults:{{ user_name }} {{ item }}
    validate: /usr/sbin/visudo -cf %s
    create: true
  become: true
  loop: "{{ user_sudo_defaults }}"

- name: Config sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ user_name }}
    line: "{{ user_name }} {{ item }}"
    validate: /usr/sbin/visudo -cf %s
    create: true
  become: true
  loop: "{{ user_sudo_privileges }}"
