# consider the following addons:
# https://github.com/peti/hledger-interest
# https://github.com/thesmokinator/hledger-textual

---
- name: Checkout finances repo
  ansible.builtin.git:
    dest: "{{ packages_hledger_path }}"
    repo: "{{ packages_hledger_repo }}"
    version: main
    accept_hostkey: true
