# consider the following addons:
# https://github.com/peti/hledger-interest
# https://github.com/thesmokinator/hledger-textual

---
- name: Checkout finances repo
  ansible.builtin.git:
    dest: "{{ packages_hledger_path }}"
    repo: "{{ packages_hledger_repo }}"
    version: main
    accept_hostkey: true

- name: Link main journal to default location
  ansible.builtin.file:
    src: "{{ packages_hledger_path }}/main.journal"
    dest: "{{ ansible_env.HOME }}/.hledger.journal"
    state: link
