---
- name: "Check if {{ app.name }} directory exists"
  ansible.builtin.stat:
    path: "{{ app.path }}"
  register: dir

- name: "Remove default {{ app.name }} config"
  ansible.builtin.file:
    path: "{{ app.path }}"
    state: absent
  when: not dir.stat.get("islnk", true)

- name: "Configure {{ app.name }}"
  ansible.builtin.file:
    src: "{{ role_path }}/files/{{ app.name }}"
    dest: "{{ app.path }}"
    state: link
    force: true
