---
- name: Add nix profile
  ansible.builtin.shell: |-
    {% if ansible_distribution != 'NixOS' %}
    . {{ packages_nix_daemon }}.sh
    {% endif %}

    nix profile add --show-trace {{ packages_nix_flake_path }}#default
    nix flake update
    nix profile upgrade --all
    nix-collect-garbage
  tags: nix
  when: packages_nix_flake_path is defined

- name: Configure software
  # I cannot use loops with import_tasks
  ansible.builtin.include_tasks: "{{ file }}.yml"
  loop:
    - alacritty
    - fish
    - git
    - go
    - fonts
    - hledger
    - nvim
    - tmux
  loop_control:
    loop_var: file

- name: Make symlinks
  ansible.builtin.include_tasks: link.yml
  loop:
    - name: niri
      path: "{{ packages_xdg_config }}/niri"
    - name: waybar
      path: "{{ packages_xdg_config }}/waybar"
    - name: nvim
      path: "{{ packages_xdg_config }}/nvim"
  loop_control:
    loop_var: app
