---
- name: Install nix
  ansible.builtin.import_tasks: nix.yml
  tags: nix

- name: Configure software
  # I cannot use loops with import_tasks
  ansible.builtin.include_tasks: "{{ file }}.yml"
  loop:
    - alacritty
    - fish
    - git
    - go
    - fonts
    - hledger
    - nvim
    - tmux
    - waybar
  tags: waybar
  loop_control:
    loop_var: file
