---
- name: Activate home
  ansible.builtin.shell: >-
    nix run github:nix-community/home-manager
    -- switch --flake .#{{ ansible_env.USER }}
  args:
    chdir: "{{ role_path }}/files/home-manager"
  tags: home-manager

- name: Configure software
  # I cannot use loops with import_tasks
  ansible.builtin.include_tasks: "{{ file }}.yml"
  loop:
    - alacritty
    - fish
    - git
    - go
    - fonts
    - hledger
    - nvim
    - tmux
  loop_control:
    loop_var: file

- name: Make symlinks
  ansible.builtin.include_tasks: link.yml
  loop:
    - name: niri
      path: "{{ packages_xdg_config }}/niri"
    - name: waybar
      path: "{{ packages_xdg_config }}/waybar"
    - name: nvim
      path: "{{ packages_xdg_config }}/nvim"
  loop_control:
    loop_var: app
