---
- name: Enable flake
  ansible.builtin.shell: |-
    {% if ansible_distribution != 'NixOS' %}
    . {{ packages_nix_daemon }}.sh
    {% endif %}

    nix profile add --show-trace {{ packages_nix_flake_path }}
    nix-collect-garbage
  when: packages_nix_flake_path is defined
