---
- name: Create directory for nvim plugin manager
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ packages_nvim_plug_path }}"

- name: Install nvim plugin manager
  ansible.builtin.get_url:
    url: "{{ packages_nvim_plug_url }}"
    dest: "{{ packages_nvim_plug_path }}"
