---

- name: Install dwl deps
  pacman:
    update_cache: true
    state: latest
    name:
      - wayland-protocols
      - wlroots
  become: true

- name: Clone dwl
  git:
    repo: "{{ wm_dwl_git_repo }}"
    dest: "{{ wm_dwl_dist }}"
    force: true

- name: Build dwl
  shell:
    cmd: make
    chdir: "{{ wm_dwl_dist }}"
  become: true

- name: Move dwl binary to PATH dir
  copy:
    src: "{{ wm_dwl_dist }}/dwl"
    dest: "{{ wm_dwl_binary }}"
    mode: 0755
    remote_src: true
  become: true

- name: Create dir for wayland sessions
  file:
    state: directory
    mode: 0755
    owner: root
    group: root
    path: "{{ wm_wayland_sessions_dir }}"
  become: true

- name: Create desktop entry
  template:
    src: dwl/dwl.desktop.j2
    dest: "{{ wm_wayland_sessions_dir }}/dwl.desktop"
  become: true
