---

- name: Install xorg
  pacman:
    state: latest
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xkbcomp
      - xf86-video-nouveau
  become: true

- name: Install suckless deps
  pacman:
    state: latest
    name:
      - make
  become: true

- name: Get suckess soft locations
  find:
    paths: "{{ wm_suckless_base_dir }}"
    file_type: directory
  register: content

- set_fact:
    wm_suckless_soft_dirs: >-
      {{ content.files | map(attribute='path') | list }}

- debug: var=wm_suckless_soft_dirs

- name: Install suckless soft
  shell: >-
    make install -C {{ item }} && make clean -C {{ item }}
  loop: "{{ wm_suckless_soft_dirs }}"
  become: true

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  become: true
  loop:
    - src: xinitrc.j2
      dest: "{{ wm_xinitrc_path }}"
    - src: xkbconf.j2
      dest: "{{ wm_xkbcomp_config_path }}"
    - src: xorg/50-touchpad.conf.j2
      dest: "{{ wm_xorg_dir }}/50-touchpad.conf"
    - src: xorg/60-mouse.conf.j2
      dest: "{{ wm_xorg_dir }}/60-mouse.conf"
