---

- name: Install sway
  pacman:
    update_cache: true
    state: latest
    name: "{{ wm_sway_packages }}"
  become: true

- name: Create dir for sway config
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ wm_sway_config_dir }}"
    - "{{ wm_waybar_config_dir }}"

- name: Configure sway
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(0644) }}"
  loop:
    - src: sway/config.j2
      dest: "{{ wm_sway_config_path }}"
    - src: sway/vars.j2
      dest: "{{ wm_sway_config_dir }}/vars"
    - src: sway/keys.j2
      dest: "{{ wm_sway_config_dir }}/keys"
    - src: sway/io.j2
      dest: "{{ wm_sway_config_dir }}/io"
    - src: sway/style.j2
      dest: "{{ wm_sway_config_dir }}/style"
    - src: waybar/config.j2
      dest: "{{ wm_waybar_config_dir }}/config"
    - src: waybar/layout.sh.j2
      mode: '0755'
      dest: "{{ wm_sway_layout_script_path }}"
    - src: waybar/style.css.j2
      dest: "{{ wm_waybar_style_path }}"
