---

- name: Install base packages
  pacman:
    update_cache: true
    state: latest
    name:
      - xorg
      - xorg-server
      - xorg-xinit
      - xorg-xkbcomp
  become: true

- name: Create dirs
  file:
    state: directory
    path: "{{ item }}"
  loop:
    - "{{ wm_xkbcomp_config_dir }}"

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
  become: true
  loop:
    - src: xinitrc.j2
      dest: "{{ wm_xinitrc_path }}"
      mode: "0755"
    - src: xkbconf.j2
      dest: "{{ wm_xkbcomp_config_path }}"
    - src: xorg/50-touchpad.conf.j2
      dest: "{{ wm_xorg_dir }}/50-touchpad.conf"
    - src: xorg/60-mouse.conf.j2
      dest: "{{ wm_xorg_dir }}/60-mouse.conf"
