---

wm_xinitrc_path: "{{ lookup('env', 'HOME') }}/.xinitrc"
wm_suckless_base_dir: "{{ playbook_dir }}/suckless"
wm_xkbcomp_config_dir: "{{ lookup('env', 'HOME') }}/.config/xkb"
wm_xkbcomp_config_path: "{{ wm_xkbcomp_config_dir }}//my"
wm_xorg_dir: /etc/X11/xorg.conf.d
wm_wayland_sessions_dir: /usr/share/wayland-sessions

wm_nvidia_driver_name: xf86-video-nouveau
wm_default_driver_name: xf86-video-vesa

wm_install_display_manager: true

wm_install_sway: true
wm_sway_packages:
  - sway
  - swaylock
  - swayidle
  - bemenu-wlroots
  - brightnessctl
  - waybar
  - mako
  - slurp
  - grim
wm_sway_config_dir: "{{ lookup('env', 'HOME') }}/.config/sway"
wm_sway_config_path: "{{ wm_sway_config_dir }}/config"
wm_waybar_config_dir: "{{ lookup('env', 'HOME') }}/.config/waybar"
wm_waybar_style_path: "{{ wm_waybar_config_dir }}/style.css"
wm_sway_layout_script_path: "{{ wm_waybar_config_dir }}/layout.sh"
wm_sway_screenshot_dir: "{{ lookup('env', 'HOME') }}/Screenshots"
