---

wm_xinitrc_path: "{{ lookup('env', 'HOME') }}/.xinitrc"
wm_suckless_base_dir: "{{ playbook_dir }}/suckless"
wm_xkbcomp_config_dir: "{{ lookup('env', 'HOME') }}/.config/xkb"
wm_xkbcomp_config_path: "{{ x11_xkbcomp_config_dir }}//my"
