---
- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: "deb http://{{ zsh_url }}/ /"
  become: true
  # NOTE: skipping because the key is expired
  when: false

- name: Add apt key
  ansible.builtin.apt_key:
    url: "https://{{ zsh_url }}/Release.key"
    validate_certs: false
  become: true
  # NOTE: skipping because the key is expired
  when: false

- name: Update packages cache
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install zsh
  ansible.builtin.package:
    name: "{{ zsh_packages }}"
    state: present
  become: true

- name: Pull oh-my-zsh
  ansible.builtin.git:
    dest: "{{ zsh_oh_my_zsh_path }}"
    repo: "{{ zsh_oh_my_zsh_repo }}"
    force: true
    accept_hostkey: true

- name: Configure
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0755"
  loop:
    - src: zshrc.j2
      dest: "{{ ansible_env.HOME }}/.zshrc"
    - src: zshenv.j2
      dest: "{{ ansible_env.HOME }}/.zshenv"
    - src: zsh_aliases.j2
      dest: "{{ ansible_env.HOME }}/.zsh_aliases"

- name: Install custom zsh theme
  ansible.builtin.import_tasks: oh-my-zsh-custom.yml

- name: Fix permissions
  ansible.builtin.file:
    path: "{{ zsh_oh_my_zsh_path }}"
    mode: "g-w,o-w"
    recurse: true

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: true
