---

- name: Install zsh
  pacman:
    update_cache: true
    name:
      - zsh
      - zsh-completions
    state: latest
  become: true

- name: Pull oh-my-zsh
  git:
    dest: "{{ zsh_oh_my_zsh_path }}"
    repo: "{{ zsh_oh_my_zsh_repo }}"
    force: true
    accept_hostkey: true

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
    - src: zshrc.j2
      dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    - src: zshenv.j2
      dest: "{{ lookup('env', 'HOME') }}/.zshenv"
    - src: zsh_aliases.j2
      dest: "{{ lookup('env', 'HOME') }}/.zsh_aliases"

- name: Create custom themes dir
  file:
    state: directory
    path: "{{ zsh_hom_my_zsh_external_themes_path }}"

- name: Download external themes
  get_url:
    url: "{{ item }}"
    dest: "{{ zsh_hom_my_zsh_external_themes_path }}"
  loop: "{{ zsh_hom_my_zsh_external_themes }}"

- name: Set zsh as default shell
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  become: true
