---

- name: Install zsh
  pacman:
    name:
      - git
      - zsh
      - zsh-completions
    state: latest
  become: true

- name: Pull oh-my-zsh
  git:
    dest: "{{ zsh_oh_my_zsh_path }}"
    repo: "{{ zsh_oh_my_zsh_repo }}"

- name: Configure
  template:
    src: "{{ item.scr }}"
    dest: "{{ item.dest }}"
  loop:
    - src: zshrc.j2
      dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    - src: zshenv.j2
      dest: "{{ lookup('env', 'HOME') }}/.zshenv"
    - src: zlogout.j2
      dest: "{{ lookup('env', 'HOME') }}/.zlogout"
