---
- name: Create custom dir
  ansible.builtin.file:
    state: directory
    path: "{{ zsh_oh_my_zsh_custom }}"

- name: Setup theme
  ansible.builtin.template:
    src: saf.zsh-theme.j2
    dest: "{{ zsh_oh_my_zsh_custom }}/saf.zsh-theme"
    mode: "0755"

- name: Create plugins dir
  ansible.builtin.file:
    state: directory
    path: "{{ zsh_oh_my_zsh_custom }}/plugins"

- name: Download plugins
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    force: true
  loop:
    - repo: https://github.com/superbrothers/zsh-kubectl-prompt
      path: "{{ zsh_oh_my_zsh_custom_plugins_dir }}/zsh-kubectl-prompt"
