---

- name: Create custom dir
  file:
    state: directory
    path: "{{ zsh_oh_my_zsh_custom }}"

- name: Download external themes
  get_url:
    url: "{{ item }}"
    dest: "{{ zsh_oh_my_zsh_custom }}"
  loop: "{{ zsh_oh_my_zsh_external_themes }}"

- name: Create plugins dir
  file:
    state: directory
    path: "{{ zsh_oh_my_zsh_custom }}/plugins"

- name: Download plugins
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.path }}"
    force: true
  loop: "{{ zsh_oh_my_zsh_external_plugins }}"
