---
packages_nix_flakes: true

packages_go_install:
  - github.com/juev/hledger-lsp/cmd/hledger-lsp@latest

packages_alacritty_config_dir: "{{ lookup('env', 'HOME') }}/.config/alacritty"

packages_fish_config_dir: "{{ lookup('env', 'HOME') }}/.config/fish"
packages_fish_go_path: "{{ ansible_env.HOME }}/go"
packages_fish_local_bin_path: "{{ ansible_env.HOME }}/.local/bin"
packages_nix_daemon: >-
  /nix/var/nix/profiles/default/etc/profile.d/nix-daemon
packages_fish_fisher_plugins:
  - jorgebucaran/fisher
  - jorgebucaran/autopair.fish
  - pure-fish/pure
  - evanlucas/fish-kubectl-completions
  - joehillen/ev-fish

packages_nvim_plug_path: >-
  {{ ansible_env.HOME }}/.local/share/nvim/site/autoload/
packages_nvim_plug_url: >-
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
packages_nvim_config_repo: "git@github.com:cornBuddy/nvim-config.git"
packages_nvim_config_path: "{{ ansible_env.HOME }}/.config/nvim"

packages_git_config: "{{ ansible_env.HOME }}/.gitconfig"
packages_git_ssh_config: "{{ ansible_env.HOME }}/.ssh/config"
packages_git_email: heorhi.sakovich@gmail.com
packages_git_signingkey: "{{ ansible_env.HOME }}/.ssh/github.pub"
packages_git_github_identity_file: "{{ ansible_env.HOME }}/.ssh/github"

packages_tmux_config_path: "{{ ansible_env.HOME }}/.tmux.conf"
packages_tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
packages_tmux_resurrect_dir: "{{ ansible_env.HOME }}/.tmux/resurrect"
packages_tmux_gitmux_config_path: "{{ ansible_env.HOME }}/.gitmux.conf"
packages_tmux_tpm_git_url: https://github.com/tmux-plugins/tpm
packages_tmux_status_battery: >-
  #{battery_icon} #{battery_percentage}
packages_tmux_status_gitmux: >-
  #[fg=brightblack,bg=black]#[fg=white,bg=brightblack]
  #(gitmux -cfg {{ packages_tmux_gitmux_config_path }}
  '#{pane_current_path}')#[bg=brightblack]
packages_tmux_status_right: >-
  #H {{ packages_tmux_status_battery }} {{ packages_tmux_status_gitmux }}

packages_hledger_version: 1.51.2
packages_hledger_repo: git@github.com:cornbuddy/finances.git
packages_hledger_path: "{{ ansible_env.HOME }}/code/finances"

packages_fonts_install: false
packages_fonts_url: https://github.com/ryanoasis/nerd-fonts.git
packages_fonts_dir: "{{ ansible_env.HOME }}/.nerd-fonts"
