---

- name: Create pacmand
  file:
    state: directory
    path: "{{ pacman_pacmand }}"
    mode: 0755
    owner: root
    group: root
  become: true

- name: Configure pacman
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
  become: true
  loop:
    - src: mirrorlist.j2
      dst: "{{ pacman_mirrorlist }}"
    - src: pacman.conf.j2
      dst: "{{ pacman_conf }}"

- import_tasks: install-trizen.yml

- name: Upgrade system
  pacman:
    update_cache: true
    upgrade: true
  become: true
