---

zsh_oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git
zsh_oh_my_zsh_path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
zsh_hom_my_zsh_external_themes_path: >-
  {{ lookup('env', 'HOME') }}/.oh-my-zsh-custom-themes
zsh_hom_my_zsh_external_themes:
  - https://gist.githubusercontent.com/cornBuddy/a6a010252e15960485fb1ce47b8635df/raw/34e5900d7f433c0b49493498e3d7e2f3989b6f98/saf.zsh-theme

zsh_local_bin_path: "{{ lookup('env', 'HOME') }}/.local/bin"
