---

- name: Install git
  package:
    name:
      - git
    state: present
  when: ansible_distribution != 'MacOSX'

- name: Configure
  template:
    src: gitconfig.j2
    dest: "{{ git_main_config_path }}"
