---

- name: Install git
  pacman:
    update_cache: true
    name:
      - git
    state: latest
  become: true

- name: Configure
  template:
    src: gitconfig.j2
    dest: "{{ git_main_config_path }}"
