---
- name: Install git
  ansible.builtin.package:
    name:
      - git
    state: present
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Configure
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: gitconfig.j2
      dest: "{{ git_main_config_path }}"
    - src: ssh-config.j2
      dest: "{{ git_ssh_config }}"
