---
- name: Install git
  ansible.builtin.package:
    name:
      - git
    state: present
  when: ansible_distribution != 'MacOSX'
  become: true

- name: Configure
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ git_main_config_path }}"
