---
- name: Configure
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  become: true
  notify: nixos rebuild
  loop:
    - src: dwm.nix.j2
      dest: "{{ nixos_config_directory }}/dwm.nix"
    - src: packages.nix.j2
      dest: "{{ nixos_config_directory }}/packages.nix"
    - src: configuration.nix.j2
      dest: "{{ nixos_config_directory }}/configuration.nix"
