---
- name: Copy dwm source
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/files/dwm/"
    dest: "{{ nixos_config_directory }}/dwm/"
  become: true
  notify: nixos rebuild

- name: Configure
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  become: true
  notify: nixos rebuild
  loop:
    - src: packages.nix.j2
      dest: "{{ nixos_config_directory }}/packages.nix"
    - src: nvidia-disable.nix.j2
      dest: "{{ nixos_config_directory }}/nvidia-disable.nix"
    - src: configuration.nix.j2
      dest: "{{ nixos_config_directory }}/configuration.nix"
