---
- name: Configure
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  become: true
  notify: Nixos rebuild
  loop:
    - src: packages.nix
      dest: "{{ nixos_config_directory }}/packages.nix"
    - src: nvidia-disable.nix
      dest: "{{ nixos_config_directory }}/nvidia-disable.nix"
    - src: configuration.nix
      dest: "{{ nixos_config_directory }}/configuration.nix"
