---
- name: Set lid close behaviour
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitch=lock
  become: true

- name: Set log max size
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: ^SystemMaxUse=
    line: SystemMaxUse=50M
  notify:
    - Restart journald
  become: true

- name: Swap Caps and Ctrl for GNOME Desktop (Non-interactive)
  community.general.dconf:
    key: /org/gnome/desktop/input-sources/xkb-options
    value: "['ctrl:swapcaps']"
    state: present

- name: Install snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(omit) }}"
  loop: "{{ ubuntu_snap_packages }}"

- name: Upgrade packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
  become: true

- name: Install niri
  ansible.builtin.import_tasks: niri.yml
  when: ubuntu_install_niri | bool
