---

tmux_config_path: "{{ lookup('env', 'HOME') }}/.tmux.conf"
tmux_plugins_dir: "{{ lookup('env', 'HOME') }}/.tmux/plugins"
tmux_tpm_git_url: https://github.com/tmux-plugins/tpm

tmux_gitmux_version: 0.7.4
tmux_gitmux_config_path: "{{ lookup('env', 'HOME') }}/.gitmux.conf"
tmux_gitmux_download_url: >-
  https://github.com/arl/gitmux/releases/download/v{{ tmux_gitmux_version }}/gitmux_{{ tmux_gitmux_version }}_linux_amd64.tar.gz
