---

- name: Download tpm
  git:
    dest: "{{ tmux_plugins_dir }}/tpm"
    repo: "{{ tmux_tpm_git_url }}"
    force: true

- name: Install tmux
  package:
    name:
      - tmux
    state: present
  become: true

- name: Install gitmux
  unarchive:
    src: "{{ tmux_gitmux_download_url }}"
    dest: /usr/local/bin
    mode: 0755
    remote_src: true
  become: true

- name: Configure
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: tmux.conf.j2
      dest: "{{ tmux_config_path }}"
    - src: gitmux.conf.j2
      dest: "{{ tmux_gitmux_config_path }}"

- name: Enable tmux-continuum
  systemd:
    state: restarted
    enabled: true
    scope: user
    name: tmux
