# Environment variables definitions
export PATH=${PATH}:./node_modules/.bin/:../node_modules/.bin:../../node_modules/.bin:../../../node_modules/.bin:../../../../node_modules/.bin:../../../../../node_modules/.bin
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:/usr/bin/scripts"
# export PATH=${PATH}:~/.npm-global/bin
export NODE_ENV=development
export EDITOR=nvim
export PAGER=less
export DOTFILES_PATH=~/.dotfiles

