# Environment variables definitions
export PATH=${PATH}:./node_modules/.bin/:../node_modules/.bin:../../node_modules/.bin:../../../node_modules/.bin:../../../../node_modules/.bin:../../../../../node_modules/.bin
export PATH=${PATH}:~/.gem/ruby/2.4.0/bin
# export PATH=${PATH}:~/.npm-global/bin
export NODE_ENV=development
export EDITOR=nvim
export PAGER=less

