# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh-history
HISTSIZE=100
SAVEHIST=100
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
[ -f ~/.zshenv_private ] && source ~/.zshenv_private
[ -f ~/.zsh_prompt ] && source ~/.zsh_prompt
if [ -f ~/.gem/ruby/2.4.0/gems/tmuxinator-0.9.0/completion/tmuxinator.zsh ]
then
    source ~/.gem/ruby/2.4.0/gems/tmuxinator-0.9.0/completion/tmuxinator.zsh
fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
