# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh-history
HISTSIZE=100
SAVEHIST=100
# 10ms for key sequences
KEYTIMEOUT=1
unsetopt beep
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit promptinit
compinit
promptinit

[ -f ~/.zsh_aliases ] && source ~/.zsh_aliases
[ -f ~/.zshenv_private ] && source ~/.zshenv_private
[ -f ~/.zsh_prompt ] && source ~/.zsh_prompt
