---

- name: Install alacritty (mac)
  community.general.homebrew_cask:
    name:
      - alacritty
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Install alacritty (linux)
  ansible.builtin.package:
    name:
      - alacritty
    state: latest
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Create config dir
  ansible.builtin.file:
    path: "{{ alacritty_config_dir }}"
    state: directory

- name: Copy config file
  ansible.builtin.template:
    src: alacritty.toml.j2
    dest: "{{ alacritty_config_dir }}/alacritty.toml"
