---

- name: Install alacritty (mac)
  homebrew_cask:
    name:
      - alacritty
    state: latest
  when: ansible_distribution == 'MacOSX'

- name: Install alacritty (linux)
  package:
    name:
      - alacritty
    state: latest
  when: ansible_distribution != 'MacOSX'
  become: true

- name: Create config dir
  file:
    path: "{{ alacritty_config_dir }}"
    state: directory

- name: Copy config file
  template:
    src: alacritty.yml.j2
    dest: "{{ alacritty_config_dir }}/alacritty.yml"
