alias tree='tree -I "jspm_packages|node_modules|bower_components|deps"'
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
# some git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit -m'
alias gd='git diff'
alias go='git checkout'
alias gp='git pull --rebase ; git push'
alias gl='git log-graph'
git() {
    if [[ $1 == "review-branch" ]]; then
        CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
        command git checkout $2
        command git pull --rebase
        command git checkout $CURRENT_BRANCH
        command git --no-pager log-specific $2 -p -U2000 --walk-reflogs $2 -- > "$2.diff"
        $EDITOR "$2.diff"
    else
        command git $@
    fi
}

alias xclip='xclip -selection clipboard'

alias c='clear'

alias tmx='tmuxinator'
