---
dependencies:
  - role: alacritty
  - role: fish
  - role: git
  - role: neovim
  - role: tmux
  - role: deekayen.awscli2
    when: ansible_distribution != 'MacOSX'
    when: packages_install_ssm
  - role: geerlingguy.nodejs
    when: packages_install_node_js
    vars:
      nodejs_version: 20.x
    become: true
  - role: gantsign.golang
    when: packages_install_go
    vars:
      golang_install_dir: "{{ packages_golang_install_dir }}"
    become: true
