---

- name: Install neovim
  package:
    state: present
    name: "{{ neovim_packages }}"
  become: false

- name: Install packer.nvim
  ansible.builtin.git:
    repo: "{{ neovim_packer_repo }}"
    dest: "{{ neovim_packer_path }}"
    depth: 1

- name: Configure
  ansible.builtin.copy:
    src: "files/nvim"
    dest: "{{ neovim_config_path }}"
