---
- name: Install neovim
  community.general.snap:
    state: present
    name: "{{ neovim_packages }}"
    classic: true
  become: true

- name: Create nvim config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ neovim_plug_path }}"

- name: Install plugin manager
  ansible.builtin.get_url:
    url: "{{ neovim_plug_url }}"
    dest: "{{ neovim_plug_path }}"

- name: Configure
  ansible.builtin.git:
    repo: "{{ neovim_config_repo }}"
    dest: "{{ neovim_config_path }}"
    force: true

- name: Sync plugins
  ansible.builtin.command: nvim --headless +PlugInstall +qa
  changed_when: false
