---
- name: nix-channel update
  listen: nixos rebuild
  command: nix-channel --update
  become: true

- name: nixos-rebuild switch
  listen: nixos rebuild
  command: nixos-rebuild switch --upgrade
  become: true

- name: nixos-rebuild boot
  listen: nixos rebuild
  command: nixos-rebuild boot
  become: true
