---
- name: &update nix-channel --update
  command: *update
  listen: Nixos rebuild
  become: true

- name: &switch nixos-rebuild switch --upgrade
  command: *switch
  listen: Nixos rebuild
  become: true

- name: &boot nixos-rebuild boot
  command: *boot
  listen: Nixos rebuild
  become: true
