---
user_name: "{{ ansible_env.USER }}"
user_shell: /bin/fish
user_secondary_groups:
  - networkmanager
  - wheel
  - input
  - docker
  - audio

user_sudo_defaults: []
user_sudo_privileges:
  - "ALL=(ALL) NOPASSWD: ALL"
