---
on:
  push:
    branches:
      - main

concurrency:
  group: "ci-${{ github.event.repository.name }}-${{ github.ref }}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: ansible-galaxy install -r requirements.yml
      - uses: pre-commit/action@v3.0.1
  release:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs:
      - lint
    steps:
      - uses: actions/checkout@v4
      - uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "main"
